apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: goodwork-pipeline
spec:
  params:
    - name: source-repo
      type: string
      description: Source code repository
    - name: image-repo
      type: string
      description: Docker image repository
  workspaces:
    - name: pipeline-shared-data
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: "$(params.source-repo)"
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: run-tests
      runAfter:
        - clone-repository
      taskRef:
        name: npm
      params:
        - name: ARGS
          value:
            - install-ci-test
      workspaces:
        - name: source
          workspace: pipeline-shared-data
    - name: build-and-push-image
      runAfter: 
        - run-tests
      taskRef:
        kind: ClusterTask
        name: buildah
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      workspaces:
        - name: source
          workspace: pipeline-shared-data      
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: goodwork-pipeline-run-
spec:
  serviceAccountName: build-bot
  pipelineRef:
    name: goodwork-pipeline
  params:
    - name: source-repo
      value: https://github.com/bjdzliu/buildah-assignment
    - name: image-repo
      value: quay.io/bjdzliu/good-work
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

